# -*- coding: utf-8 -*-
"""first.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NE0PZcU2Jx0RD3J-KaLYoOV0ufaCJBV_
"""

from langchain_openai import ChatOpenAI
from langchain_community.tools import DuckDuckGoSearchResults
from langchain_core.callbacks import StreamingStdOutCallbackHandler
from langgraph.prebuilt import create_react_agent
def search_agent():
  api_key = "sk-or-v1-................................................."
  llm = ChatOpenAI(
      api_key=api_key,
      base_url="https://openrouter.ai/api/v1",
      model="gpt-4o-mini",
      temperature=0.7,
      streaming=True,
      callbacks=[StreamingStdOutCallbackHandler()]
  )

  tools = [DuckDuckGoSearchResults(max_results=3)]


  app = create_react_agent(llm, tools)

  print("AGENT READY 100%!")

  result = app.invoke({
      "messages": [("human", "LangChain latest features?")]
  })

  print("\nSUCCESS")
  print(result["messages"][-1].content)